name: Package extract

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ cat package.json grep version head -1 awk -F: '{ print $2 }'sed 's/[",]//g' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Echo version
        run: echo "The PACKAGE_VERSION is ${{ PACKAGE_VERSION }}"


